/*
 * gpio_test.c
 *
 *  Created on: Mar 11, 2026
 *      Author: oscar
 */

#include "gpio_test.h"

void gpio_init(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	GPIOB->MODER &= ~GPIO_MODER_MODER2; // clear GPIO
	GPIOB->MODER |= GPIO_MODER_MODER2_0;
	GPIOB->MODER &= ~GPIO_MODER_MODER2_1;
	GPIOB->OTYPER &= ~ GPIO_OTYPER_OT2;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_1;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR2_0;
	GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR2_1;
}
